### ISSUE TITLE
Blocked loading mixed active conten

### ISSUE THREAD

**Issue by Conando025** [yewstack/yew-playground#4] opened 2022-10-28 14:01 UTC
The compile request has an http location header which is blocked by Firefox as it is mixed active content at least that's how I under stand it. I have the error message below
`Blocked loading mixed active content “http://playground-backend-iob5vy5ctq-uw.a.run.app/api/run?code=%0Ause+yew%3A%3Aprelude%3A%3A%2A%3B%0A%0A%23%5Bfunction_component%28App%29%5D%0Afn+app%28%29+-%3E+Html+%7B%0A++++html%21+%7B+%22hello+world%22+%7D%0A%7D%0A%0Afn+main%28%29+%7B%0A++++yew%3A%3Astart_app%3A%3A%3CApp%3E%28%29%3B%0A%7D%0A”`

**Comment by hamza1311** [comment] 2022-10-28 14:08
i have tested it with firefox and it works. Maybe there is an extension causing problem for you

**Comment by Conando025** [comment] 2022-10-28 14:35
Strange, so i first understood it wrong. My client makes the request and gets the response header but due to the location attribute of the response containing an http instead of an https adress the response body gets blocked. But from what mdn says that seems to be default behavior so not sure what is actually causing the issue

**Comment by Conando025** [comment] 2022-10-28 14:42
Did you test on your own Firefox instance if so can you check if you set "security.mixed_content.block_active_content" in the about:config to false?

**Comment by hamza1311** [comment] 2022-10-28 14:48
![image](https://user-images.githubusercontent.com/47357913/198654926-fd814104-933d-47b6-b3eb-04b7cc20739f.png)

I have it set to true. Can you post a screenshot of your network tab?
The location header returns http for me too (this is controlled by firebase)

![image](https://user-images.githubusercontent.com/47357913/198656288-080910b2-2c43-4093-9075-d4042cc77013.png)
but the redirect request is sent as https
![image](https://user-images.githubusercontent.com/47357913/198656846-5ca67f37-f59e-4251-b320-45ae8b3ed90e.png)

**Comment by hamza1311** [comment] 2022-10-28 14:50
The API is also available at https://api.play.yew.rs so instead of doing a `/api/<path>` redirect, we could make a request to `https://api.play.yew.rs/<path>`

**Comment by Conando025** [comment] 2022-10-28 14:55
![image](https://user-images.githubusercontent.com/37964708/198660868-a8913b1b-66ac-4fa5-95a7-c710ac38cb28.png)
Yeah I saw that when visiting directly it upgrades the connection to https but for me it gets blocked before following the redirect

**Comment by Conando025** [comment] 2022-10-28 15:02
I also get an http/3 response maybe thats the issue but that just creates the new question why the the http version is diffrent

**Comment by hamza1311** [comment] 2022-10-28 16:21
This should've been the first question but what version of Firefox and what OS are you on?

**Comment by Conando025** [comment] 2022-10-28 18:48
Sorry should have provided that earlier Firefox 106.0.1 on Linux (popos)

**Comment by DarylPinto** [comment] 2022-11-15 03:46
The same `Mixed Content` error occurs in Chrome with no extensions: 

![image](https://user-images.githubusercontent.com/13127692/201821426-ee2d7ca9-1a2f-4e1a-af61-034f910f3d1e.png)

OS: MacOS 12.2.1
Chrome: 107.0.5304.87 (Official Build) (arm64)

**Comment by ChristopherPerry6060** [comment] 2022-11-15 13:59
Similar issue on Windows in Vivaldi (chrome based), tried in a private window with extensions off and the issue persists. Same thing with mostly all security features disabled.

![image](https://user-images.githubusercontent.com/89366859/201936472-8f965b89-25a4-4d85-80eb-784473676896.png)

![image](https://user-images.githubusercontent.com/89366859/201937617-792a6032-c51d-4e42-b34e-b1341d76330a.png)

**Comment by houseofmercy-github** [comment] 2022-11-15 22:03
Browser: **Firefox 107.0 (64-bit)**
OS: **macOS** 10.15.7 (Catalina) 
Seeing the same issue.  Steps to reproduce:
* open https://play.yew.rs
* press **Run**
* observe blank white window appears
* Web Developer Tools Console shows error

`Blocked loading mixed active content “http://playground-backend-iob5vy5ctq-uw.a.run.app/api/run?code=%0Ause+yew%3A%3Aprelude%3A%3A%2A%3B%0A%0A%23%5Bfunction_component%28App%29%5D%0Afn+app%28%29+-%3E+Html+%7B%0A++++html%21+%7B+%22hello+world%22+%7D%0A%7D%0A%0Afn+main%28%29+%7B%0A++++yew%3A%3Astart_app%3A%3A%3CApp%3E%28%29%3B%0A%7D%0A” play.yew.rs`
 
![play yew rs run error](https://user-images.githubusercontent.com/103275384/202034426-70902a2f-5caf-4c9e-b789-afa567965af5.png)

**Comment by hamza1311** [comment] 2022-11-16 14:57
I think Google is to blame here. Firebase rewrites are used for for redirect and it returns `http` link for the cloud run service: https://firebase.google.com/docs/hosting/cloud-run. Browsers don't like http link here, perhaps because there's WASM bytes inlined in the `<script>`.

If anyone knows a fix for this, I would be happy to hear it.

**Comment by ChristopherPerry6060** [comment] 2022-11-18 13:02
Dug around a bit and found a more specific blurb from the firebase docs

> Cloud Run redirects all HTTP requests to HTTPS but terminates TLS before they reach your web service. If your service generates a web resources that refers to other web resources with unsecured URLs (http://), your page may be subject to [mixed content warnings or errors](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content). Use the https protocol for all reference web URIs or account for proxy directives in the HTTP Request such as the X-Forwarded-Proto HTTP header.

I am guessing there is a unsecured URL being called somewhere. Pretty sure it is not due to the WASM or firebase specifically since they should be redirecting everything to https. I can try to look around this weekend. Pretty unfamiliar with the codebase though @hamza1311

**Comment by hamza1311** [comment] 2022-11-20 14:11
@ChristopherPerry6060 actually this redirect is from Firebase Hosting to Cloud Run, not _between_ Cloud Run services.

The request is supposed to go as follows:
- Run button is clicked
- /api/run is called
- Firebase hosting sees the redirect and sends it off to cloud run
- Cloud run services do the computation
- response is sent is back

The third step is where the issue occurs. The communication between the cloud run services isn't exposed at all

**Comment by hamza1311** [comment] 2022-12-10 11:34
I've pushed a workaround that should fix this issue. It no longer goes through any redirects to reach the server

**Closed by hamza1311** 2022-12-10 11:34 UTC
