### ISSUE TITLE
Error message when running code in Yew Playground

### ISSUE THREAD

**Issue by leonardoSaaads** [yewstack/yew-playground#9] opened 2023-08-30 21:51 UTC
Hello,

I recently visited the Yew website (https://yew.rs/) using the Microsoft Edge browser and clicked on the "Playground" link, which took me to the Yew Playground website (https://play.yew.rs/). When I tried to run the initial code by clicking the "Run" button, I received the following error message: "upstream connect error or disconnect/reset before headers. reset reason: remote reset."

I tried running the code again, but the same error message appeared. I also tried refreshing the page and clearing my browser cache, but the error persisted. Can you please help me understand what is causing this error and how it can be resolved?

Thank you.

**Comment by hamza1311** [comment] 2023-09-05 19:43
Closing this as it is a duplicate of #8

**Closed by hamza1311** 2023-09-05 19:43 UTC

**Comment by hamza1311** [comment] 2023-09-05 20:08
This issue is also now fixed
